### ISSUE TITLE
Use buf for cusf_sidechain_proto

### ISSUE THREAD

**Issue by nchashch** [LayerTwo-Labs/bip300301_enforcer#12]

**Comment by torkelrogstad** [comment]
If we're going to use Buf for `cusf_sidechain_proto` we should use it for the Proto file in this repo as well, IMO.

**Comment by nchashch** [comment]
I moved the `mainchain.proto` file that is used by Thunder into this repo in #16 , and `sidechain.proto` isn't used by Thunder so we will just delete it.

So after Thunder is updated to use the `mainchain.proto` definition from this repo using buf, we can close this issue.

**Comment by nchashch** [comment]
I'll delete the sidechain client code, because Thunder won't run a gRPC server.

**Comment by nchashch** [comment]
I am closing this, because we decided to use a submodule referring to

https://github.com/LayerTwo-Labs/cusf_sidechain_proto

instead of buf for now.
