### ISSUE TITLE
Implement "mining" blocks in regtest mode

### ISSUE THREAD

**Issue by nchashch** [LayerTwo-Labs/bip300301_enforcer#37]
There is already an implementation of this in the `bip300301_wallet` repository, just move it here.

**Comment by torkelrogstad** [comment]
What's your opinion on the idea brought up in this discussion in the protos repo?

https://github.com/LayerTwo-Labs/cusf_sidechain_proto/pull/5#discussion_r1793646099

I've implemented functionality for adding coinbase messages to the signet miner here: https://github.com/LayerTwo-Labs/bitcoin-patched/pull/6

Doing this approach in regtest as well could be a good way of testing that it works properly. And it would let us omit the `generate` RPC

**Comment by nchashch** [comment]
It would be easier to copy over the block construction from `bip300301_wallet` implementation.

**Comment by nchashch** [comment]
Yes, but we need to get it to work with regtest first. We can worry about signet later.
