### ISSUE TITLE
Consider using `diesel` as an ORM for dealing with SQLite

### ISSUE THREAD

**Issue by nchashch** [LayerTwo-Labs/bip300301_enforcer#47]

**Comment by nchashch** [comment]
Another option is https://docs.rs/serde_rusqlite/latest/serde_rusqlite/

**Comment by torkelrogstad** [comment]
My suggestion is to avoid using ORMs, and instead be as close to raw SQL as possible. ORMs in my opinion provide little clear benefit, and mostly lead to head scratching

**Comment by nchashch** [comment]
Since we are not using SQLite that much I think an ORM would be overkill, it would just make the code more complicated without much benefit. So I'll close this one.
