### ISSUE TITLE
Implement a separate ergonomic CLI client to interact with the RPCs

### ISSUE THREAD

**Issue by nchashch** [LayerTwo-Labs/bip300301_enforcer#73]
That would improve development workflow.

**Comment by torkelrogstad** [comment]
`buf curl`? That's what I'm using

**Comment by nchashch** [comment]
> `buf curl`? That's what I'm using

It would make sense to pick a tool and then add an example of how to use it for testing the RPCs manually to the README.md file.

That would be a better option than implementing a custom CLI.

**Comment by torkelrogstad** [comment]
There's already a simple example at the bottom of the "getting started" section. https://github.com/LayerTwo-Labs/bip300301_enforcer?tab=readme-ov-file#getting-started

I could expand on that!

**Comment by nchashch** [comment]
> There's already a simple example at the bottom of the "getting started" section. https://github.com/LayerTwo-Labs/bip300301_enforcer?tab=readme-ov-file#getting-started
> 
> I could expand on that!

Yes! Adding an example for how to call a method that takes arguments would be great.
